### ISSUE TITLE
stopped working with jest 25.4.0

### ISSUE THREAD

**Issue by regevbr** [gabrieli/jest-serial-runner#6]
When using jest 25, the following error occurs:

```sh
    TypeError: runtime.unstable_shouldLoadAsEsm is not a function

      at jasmine2 (node_modules/jest-config/node_modules/jest-jasmine2/build/index.js:188:25)
```

This is because the runner is using old jest-runner.
I think the best solution is to put the jest-runner as peer dependency with no semver restrictions

**Comment by Narretz** [comment]
The quick solution is to copy the index.js file to your project, and point the runner config entry to it.
I've tested it with jest 26.6.3 and it works. Just make sure you have all jest related packages at the same version.

**Comment by jessevdp** [comment]
jest-runner should probably be listed as a peer dependency right?

I've been unraveling this thread... https://github.com/playwright-community/jest-playwright/issues/665. Currently having issues with Jest 27, and the v24 that this package specifies.

(Or maybe remove the restraint on the major version?)

**Comment by jessevdp** [comment]
@Narretz how do you point jest at a local file for running? It seems to only accept the name of a node module as a runner.

**Comment by gabrieli** [comment]
There's a new version 1.2.0 that should fix this now.
